### ISSUE TITLE
[Github] feat: removed sizes from the meta apple-touch-icon

### ISSUE THREAD

**Issue by shopwareBot** [shopware/platform#5445]
### 1. Why is this change necessary?
see #5281
see https://webhint.io/docs/user-guide/hints/hint-apple-touch-icons/#:~:text=When%20using%20one%20image%2C%20there%20is%20no%20need%20to%20use%20the

### 3. Describe each step to reproduce the issue or behaviour.
see #5281

### 4. Please link to the relevant issues (if any).
#5281

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

---

Imported from Github. Please see: https://github.com/shopware/shopware/pull/5282

**Comment by shopwareBot** [comment]
[public] 

 > Status Change: **Open**

 This issue is ready for implementation.

 

[created from NEXT-39513, comment 511541]

**Comment by shopwareBot** [comment]
[public] Shopware automated response: This issue is linked to the internal issue: **NEXT-39513**



[created from NEXT-39513, comment 511542]

**Comment by shopwareBot** [comment]
[public]

 > Status Change: **In Progress**

 Work on this issue has started. It is now being implemented.

 

[created from NEXT-39513, comment 512024]

**Comment by shopwareBot** [comment]
[public]

 > Status Change: **In Review**

 Work on this ticket is complete and is now pending review.



[created from NEXT-39513, comment 512033]

**Comment by shopwareBot** [comment]
[public]

 > Status Change: **Resolved**

 The ticket has been successfully completed; the solution is implemented and verified.



[created from NEXT-39513, comment 512124]

**Comment by shopwareBot** [comment]
[public] 

 > FixVersion Change: **6.6.9.0**

 This issue will be / was solved in Shopware version ***6.6.9.0***.



[created from NEXT-39513, comment 512125]
