### ISSUE TITLE
[Github] Add created-at colum to manually generated coupon codes

### ISSUE THREAD

**Issue by shopwareBot** [shopware/platform#5801]
### 1. Why is this change necessary?

As a shop owner I generate some new codes and want to pass them on to the customer. But I have no chance to see which codes I just generated.

### 2. What does this change do, exactly?

Adds a column "created at" to the coupon codes

![Demo](https://github.com/user-attachments/assets/4d57114e-c73f-4921-854f-f3d7b043b191)

### 3. Describe each step to reproduce the issue or behaviour.

* Generate codes
* See them in the list

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### 6. Todos

- [x] Add translations
- [?] Tests necessary?

---

Imported from Github. Please see: https://github.com/shopware/shopware/pull/5792

**Comment by shopwareBot** [comment]
[public] Shopware automated response: This issue is linked to the internal issue: **NEXT-40011**



[created from NEXT-40011, comment 524675]

**Comment by shopwareBot** [comment]
[public] 

 > FixVersion Change: **6.6.10.0**

 This issue will be / was solved in Shopware version ***6.6.10.0***.



[created from NEXT-40011, comment 524801]
