### ISSUE TITLE
[Github] #4800 Add field for meta author and use it in frontend

### ISSUE THREAD

**Issue by shopwareBot** [shopware/platform#5815]
### 1. Why is this change necessary?

See #4800 

### 2. What does this change do, exactly?

Add a configuration field to set a meta author and use it in the frontend.

### 3. Describe each step to reproduce the issue or behaviour.

See #4800 

### 4. Please link to the relevant issues (if any).

#4800 

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [ ] ~I have written tests and verified that they fail without my change~
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] ~I have written or adjusted the documentation according to my changes~
- [ ] ~This change has comments for package types, values, functions, and non-obvious lines of code~
- [X] I have read the contribution requirements and fulfill them.

---

Imported from Github. Please see: https://github.com/shopware/shopware/pull/4968

**Comment by shopwareBot** [comment]
[public] Shopware automated response: This issue is linked to the internal issue: **NEXT-40034**



[created from NEXT-40034, comment 525654]

**Comment by shopwareBot** [comment]
[public] 

 > FixVersion Change: **6.6.10.0**

 This issue will be / was solved in Shopware version ***6.6.10.0***.



[created from NEXT-40034, comment 529651]
